### PR TITLE
Bugfix: Compile on GHC 9.6.2

### LINKED ISSUE #4: GHC 6, base 4.18 support - Could not deduce Functor
I'm trying to compile Kernmantle with GHC 9.6.2 / base 4.18, and I'm getting the following error.  I've forked the repo and was hoping to add a fix, but I'm afraid I don't understand what's going on with those deriving clauses well enough to know what to do. 

Could you point me in the right direction for a fix for this? I'd be happy to create a PR. 

```

src/Control/Kernmantle/Rope/Internal.hs:88:13: error: [GHC-39999]
    • Could not deduce ‘Functor
                          (RopeRunner record mantle interp core a)’
        arising from the head of a quantified constraint
        arising from the 'deriving' clause of a data type declaration
      from the context: Bifunctor core
        bound by the deriving clause for ‘Bifunctor
                                            (RopeRunner record mantle interp core)’
        at src/Control/Kernmantle/Rope/Internal.hs:88:13-21
    • When deriving the instance for (Bifunctor
                                        (RopeRunner record mantle interp core))
   |
88 |   deriving (Bifunctor, Biapplicative)
```

### PR DESCRIPTION
**Pull request by seanhess**
Fixes #4

`*` is deprecated in favor of `Type`
`Functor` is now a prerequisite for `Bifunctor`

Let me know if anything needs to be changed! Thanks for your hard work on this.

### CODE REVIEW

**Comment by GuillaumeDesforges** [comment]
Hi @seanhess , thanks a lot for pushing this fix!

The changes look reasonable to me. :+1:

If possible I would prefer to have atomic commits. Can we make the fix of #4 and the changes from `*` to `Type` to be two different PRs, or at least two commits?

**Comment by seanhess** [comment]
Sure, I'd be happy to do that. Should have them in a few minutes. Although, to play devil's advocate, they are both fixes that were necessary to get it to compile with 9.6.2.
